import { BookmarkDto, CurriGroup } from '@/Interfaces';
export const scheduledData: BookmarkDto[] = [
  {
    subject_id: '90641001',
    subject_tname: 'โรงเรียนสร้างเสน่ห์',
    subject_ename: 'CHARM SCHOOL',
    credit: 2,
    category: 1,
    group: 32,
    subgroup: 0,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90641002',
    subject_tname: 'ความฉลาดทางดิจิทัล',
    subject_ename: 'DIGITAL INTELLIGENCE QUOTIENT',
    credit: 3,
    category: 1,
    group: 32,
    subgroup: 0,
    semester: '2',
    year: '2021',
  },
];
export const transcriptData = [
  {
    subject_id: '90641001',
    subject_tname: 'โรงเรียนสร้างเสน่ห์',
    subject_ename: 'CHARM SCHOOL',
    credit: 2,
    category: 1,
    group: 32,
    subgroup: 0,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90641002',
    subject_tname: 'ความฉลาดทางดิจิทัล',
    subject_ename: 'DIGITAL INTELLIGENCE QUOTIENT',
    credit: 3,
    category: 1,
    group: 32,
    subgroup: 0,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '90641003',
    subject_tname: 'กีฬาและนันทนาการ',
    subject_ename: 'SPORTS AND RECREATIONAL ACTIVITIES',
    credit: 1,
    category: 1,
    group: 32,
    subgroup: 0,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90644008',
    subject_tname: 'ภาษาอังกฤษพื้นฐาน 2',
    subject_ename: 'FOUNDATION ENGLISH 2',
    credit: 3,
    category: 1,
    group: 33,
    subgroup: 1,
    semester: null,
    year: null,
  },
  {
    subject_id: '90642036',
    subject_tname: 'เตรียมความพร้อมสำหรับวิศวกร',
    subject_ename: 'PRE-ACTIVITIES FOR ENGINEERS',
    credit: 1,
    category: 1,
    group: 46,
    subgroup: 1,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90642118',
    subject_tname: 'โปรแกรมคอมพิวเตอร์ประยุกต์ทางธุรกิจ',
    subject_ename: 'APPLICATION SOFTWARE FOR BUSSINESS',
    credit: 2,
    category: 1,
    group: 46,
    subgroup: 1,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '90642003',
    subject_tname: 'ปฏิบัติงานตามทักษะด้านบุคคลและสนับสนุนวิชาชีพ 3',
    subject_ename: 'PRACTICE UNDER PERSONAL AND PROFESSIONAL SKILLS 3',
    credit: 3,
    category: 1,
    group: 46,
    subgroup: 3,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '90642116',
    subject_tname: 'เมืองอัจฉริยะและนวัตกรรมเมือง',
    subject_ename: 'SMART CITY AND CITY INNOVATION',
    credit: 3,
    category: 1,
    group: 46,
    subgroup: 3,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90643016',
    subject_tname: 'สนุกกับธุรกิจออนไลน์',
    subject_ename: 'FUN WITH ONLINE BUSINESS',
    credit: 3,
    category: 1,
    group: 46,
    subgroup: 4,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '90643019',
    subject_tname: 'เศรษฐศาสตร์กับการเป็นผู้ประกอบการ',
    subject_ename: 'ECONOMICS AND ENTREPRENEURSHIP',
    credit: 3,
    category: 1,
    group: 46,
    subgroup: 4,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076032',
    subject_tname: 'สมการอนุพันธ์และพีชคณิตเชิงเส้นพื้นฐาน',
    subject_ename: 'ELEMENTARY DIFFERENTIAL EQUATIONS AND LINEAR ALGEBRA',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 1,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076140',
    subject_tname: 'แคลคูลัส 1',
    subject_ename: 'CALCULUS 1',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 1,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '01076141',
    subject_tname: 'แคลคูลัส 2',
    subject_ename: 'CALCULUS 2',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 1,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076253',
    subject_tname: 'ความน่าจะเป็นและสถิติ',
    subject_ename: 'PROBABILITY AND STATISTICS',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 1,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01006004',
    subject_tname: 'การฝึกงานอุตสาหกรรม',
    subject_ename: 'INDUSTRIAL TRAINING',
    credit: 0,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '3',
    year: '2023',
  },
  {
    subject_id: '01076011',
    subject_tname: 'ระบบปฏิบัติการ',
    subject_ename: 'OPERATING SYSTEMS',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076012',
    subject_tname: 'โครงสร้างแบบดิสครีต',
    subject_ename: 'DISCRETE STRUCTURE',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076016',
    subject_tname: 'การเตรียมโครงงานวิศวกรรมคอมพิวเตอร์',
    subject_ename: 'COMPUTER ENGINEERING PROJECT PREPARATION',
    credit: 2,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076101',
    subject_tname: 'วิศวกรรมคอมพิวเตอร์เบื้องต้น',
    subject_ename: 'INTRODUCTION TO COMPUTER ENGINEERING',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '01076103',
    subject_tname: 'พื้นฐานการเขียนโปรแกรมคอมพิวเตอร์',
    subject_ename: 'PROGRAMMING FUNDAMENTAL',
    credit: 2,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '01076104',
    subject_tname: 'โครงงานโปรแกรมคอมพิวเตอร์',
    subject_ename: 'PROGRAMMING PROJECT',
    credit: 1,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '01076107',
    subject_tname: 'วงจรไฟฟ้าและอิเล็กทรอนิกส์',
    subject_ename: 'CIRCUITS AND ELECTRONICS',
    credit: 3,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076108',
    subject_tname: 'ปฏิบัติการวงจรไฟฟ้าและอิเล็กทรอนิกส์',
    subject_ename: 'CIRCUITS AND ELECTRONICS IN PRACTICE',
    credit: 1,
    category: 2,
    group: 100,
    subgroup: 2,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076034',
    subject_tname: 'หลักการของกระบวนการพัฒนาซอฟต์แวร์',
    subject_ename: 'PRINCIPLES OF SOFTWARE DEVELOPMENT PROCESS',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076040',
    subject_tname: 'มาตรฐานและเทคโนโลยีเครือข่าย',
    subject_ename: 'INTERNETWORKING STANDARDS AND TECHNOLOGIES',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076041',
    subject_tname: 'ปฏิบัติการมาตรฐานและเทคโนโลยีเครือข่าย',
    subject_ename: 'INTERNETWORKING STANDARDS AND TECHNOLOGIES IN PRACTICE',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076050',
    subject_tname: 'การประยุกต์และพัฒนาไมโครคอนโทรลเลอร์',
    subject_ename: 'MICROCONTROLLER APPLICATION AND DEVELOPMENT',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076051',
    subject_tname: 'โครงงานไมโครคอนโทรลเลอร์',
    subject_ename: 'MICROCONTROLLER PROJECT',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076105',
    subject_tname: 'การเขียนโปรแกรมเชิงวัตถุ',
    subject_ename: 'OBJECT ORIENTED PROGRAMMING',
    credit: 2,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076106',
    subject_tname: 'โครงงานโปรแกรมเชิงวัตถุ',
    subject_ename: 'OBJECT ORIENTED PROGRAMMING PROJECT',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '2',
    year: '2021',
  },
  {
    subject_id: '01076109',
    subject_tname: 'โครงสร้างข้อมูลเชิงวัตถุ',
    subject_ename: 'OBJECT ORIENTED DATA STRUCTURES',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076110',
    subject_tname: 'โครงงานโครงสร้างข้อมูลเชิงวัตถุ',
    subject_ename: 'OBJECT ORIENTED DATA STRUCTURES PROJECT',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076112',
    subject_tname: 'พื้นฐานระบบดิจิตอล',
    subject_ename: 'DIGITAL SYSTEM FUNDAMENTALS',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076113',
    subject_tname: 'ปฏิบัติการพื้นฐานระบบดิจิตอล',
    subject_ename: 'DIGITAL SYSTEM FUNDAMENTALS IN PRACTICE',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076114',
    subject_tname: 'องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์',
    subject_ename: 'COMPUTER ORGANIZATION AND ARCHITECTURE',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076115',
    subject_tname: 'ปฏิบัติการองค์ประกอบคอมพิวเตอร์\t',
    subject_ename: 'COMPUTER ORGANIZATION IN PRACTICE',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 5,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076116',
    subject_tname: 'เครือข่ายคอมพิวเตอร์',
    subject_ename: 'COMPUTER NETWORKS',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076117',
    subject_tname: 'ปฏิบัติการเครือข่ายคอมพิวเตอร์',
    subject_ename: 'COMPUTER NETWORKS IN PRACTICE',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076118',
    subject_tname: 'การดูแลแพลทฟอร์มระบบ',
    subject_ename: 'SYSTEM PLATFORM ADMINISTRATION',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '01076119',
    subject_tname: 'การพัฒนาโปรแกรมบนเว็บ',
    subject_ename: 'WEB APPLICATION DEVELOPMENT',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076120',
    subject_tname: 'โครงงานพัฒนาโปรแกรมบนเว็บ',
    subject_ename: 'WEB APPLICATION DEVELOPMENT PROJECT',
    credit: 1,
    category: 2,
    group: 101,
    subgroup: 3,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076121',
    subject_tname: 'ทฤษฎีการคำนวณ',
    subject_ename: 'THEORY OF COMPUTATION',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 4,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076263',
    subject_tname: 'ระบบฐานข้อมูล\t',
    subject_ename: 'DATABASE SYSTEMS',
    credit: 3,
    category: 2,
    group: 101,
    subgroup: 2,
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076311',
    subject_tname: 'โครงงาน 1',
    subject_ename: 'PROJECT 1',
    credit: 3,
    category: 2,
    group: 102,
    subgroup: 1,
    semester: '1',
    year: '2024',
  },
  {
    subject_id: '01076423',
    subject_tname: 'การวางแผนเชิงกลยุทธ์โดยใช้บอร์ดและการ์ดเกม',
    subject_ename: 'STRATEGIC PLANNING USING BOARD AND CARD GAME',
    credit: 3,
    category: 2,
    group: 103,
    subgroup: 8,
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076567',
    subject_tname: 'การประมวลผลภาพ\t',
    subject_ename: 'IMAGE PROCESSING',
    credit: 3,
    category: 2,
    group: 103,
    subgroup: 4,
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076582',
    subject_tname: 'ปัญญาประดิษฐ์\t',
    subject_ename: 'ARTIFICIAL INTELLIGENCE',
    credit: 3,
    category: 2,
    group: 103,
    subgroup: 5,
    semester: '2',
    year: '2024',
  },
  {
    subject_id: '01076595',
    subject_tname: 'การสืบค้นสารสนเทศและการค้นหาเว็บ',
    subject_ename: 'INFORMATION STORAGE AND WEB SEARCH',
    credit: 3,
    category: 2,
    group: 103,
    subgroup: 5,
    semester: '1',
    year: '2024',
  },
];

const unknow = [
  {
    subject_id: '90644014',
    subject_tname: 'ภาษาอังกฤษเพื่อการสื่อสารทางวิชาชีพ',
    subject_ename: 'ENGLISH FOR PROFESSIONAL COMMUNICATION',
    credit: 3,
    category: [1, 1],
    group: [33, 46],
    subgroup: [2, 5],
    semester: '1',
    year: '2021',
  },
  {
    subject_id: '90644033',
    subject_tname: 'การเขียนและการพูดในงานอาชีพ',
    subject_ename: 'WRITING AND SPEAKING IN THE PROFESSIONS',
    credit: 3,
    category: [1, 1],
    group: [33, 46],
    subgroup: [2, 5],
    semester: '1',
    year: '2022',
  },
  {
    subject_id: '90592004',
    subject_tname: 'วัฒนธรรมร่วมสมัย',
    subject_ename: 'CONTEMPORARY CULTURE',
    credit: 3,
    category: null,
    group: null,
    subgroup: null,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '96642111',
    subject_tname: 'FUN WITH CODING',
    subject_ename: 'FUN WITH CODING',
    credit: 3,
    category: null,
    group: null,
    subgroup: null,
    semester: '2',
    year: '2022',
  },
  {
    subject_id: '01076036',
    subject_tname: 'การออกแบบประสบการณ์และส่วนติดต่อผู้ใช้',
    subject_ename: 'USER EXPERIENCE AND USER INTERFACE DESIGN',
    credit: 2,
    category: [2, 2],
    group: [101, 103],
    subgroup: [8, 9],
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076037',
    subject_tname: 'โครงงานออกแบบประสบการณ์และส่วนติดต่อผู้ใช้',
    subject_ename: 'USER EXPERIENCE AND USER INTERFACE PROJECT',
    credit: 1,
    category: [2, 2],
    group: [101, 103],
    subgroup: [8, 9],
    semester: '1',
    year: '2023',
  },
  {
    subject_id: '01076035',
    subject_tname: 'กระบวนการพัฒนาซอฟต์แวร์เชิงปฏิบัติ',
    subject_ename: 'SOFTWARE DEVELOPMENT PROCESS IN PRACTICE',
    credit: 3,
    category: [2, 2],
    group: [101, 103],
    subgroup: [8, 9],
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '01076042',
    subject_tname: 'ความมั่นคงข้อมูลและคอมพิวเตอร์',
    subject_ename: 'INFORMATION AND COMPUTER SECURITY',
    credit: 3,
    category: [2, 2],
    group: [101, 103],
    subgroup: [9, 9],
    semester: '2',
    year: '2023',
  },
  {
    subject_id: '90644063',
    subject_tname: 'ภาษาญี่ปุ่นเพื่อการท่องเที่ยว',
    subject_ename: 'JAPANESE FOR TRAVEL',
    credit: 3,
    category: [1, 1],
    group: [33, 46],
    subgroup: [2, 5],
    semester: '2',
    year: '2024',
  },
];

export const responseApiTranscript = {
  status: true,
  path: '/transcript',
  message: 'success',
  statusCode: 201,
  data: {
    result: {
      categorizedResult: [
        {
          category: 1,
          group: 32,
          subgroup: 0,
          credit1: 6,
          credit2: 6,
          categoryName: 'วิชาศึกษาทั่วไป',
          groupName: 'กลุ่มวิชาภาษา',
          subgroupName: null,
          earnCredit: 6,
          subjects: [
            {
              subject_id: '90641001',
              category: '1',
              group: '32',
              subgroup: '0',
              subject_tname: 'โรงเรียนสร้างเสน่ห์',
              subject_ename: 'CHARM SCHOOL',
              credit: 2,
            },
            {
              subject_id: '90641002',
              category: '1',
              group: '32',
              subgroup: '0',
              subject_tname: 'ความฉลาดทางดิจิทัล',
              subject_ename: 'DIGITAL INTELLIGENCE QUOTIENT',
              credit: 3,
            },
            {
              subject_id: '90641003',
              category: '1',
              group: '32',
              subgroup: '0',
              subject_tname: 'กีฬาและนันทนาการ',
              subject_ename: 'SPORTS AND RECREATIONAL ACTIVITIES',
              credit: 1,
            },
          ],
        },
        {
          category: 1,
          group: 33,
          subgroup: 1,
          credit1: 6,
          credit2: 6,
          categoryName: 'วิชาศึกษาทั่วไป',
          groupName: 'กลุ่มวิชาด้านภาษาและการสื่อสาร',
          subgroupName: 'กลุ่มภาษาและการสื่อสารบังคับ',
          earnCredit: 6,
          subjects: [
            {
              subject_id: '90644007',
              category: '1',
              group: '33',
              subgroup: '1',
              subject_tname: 'ภาษาอังกฤษพื้นฐาน 1',
              subject_ename: 'FOUNDATION ENGLISH 1',
              credit: 3,
            },
            {
              subject_id: '90644008',
              category: '1',
              group: '33',
              subgroup: '1',
              subject_tname: 'ภาษาอังกฤษพื้นฐาน 2',
              subject_ename: 'FOUNDATION ENGLISH 2',
              credit: 3,
            },
          ],
        },
        {
          category: 1,
          group: 33,
          subgroup: 2,
          credit1: 3,
          credit2: 3,
          categoryName: 'วิชาศึกษาทั่วไป',
          groupName: 'กลุ่มวิชาด้านภาษาและการสื่อสาร',
          subgroupName: 'กลุ่มภาษาและการสื่อสารเลือก',
          earnCredit: 0,
          subjects: [],
        },
        {
          category: 1,
          group: 46,
          subgroup: 1,
          credit1: 3,
          credit2: 3,
          categoryName: 'วิชาศึกษาทั่วไป',
          groupName: 'กลุ่มวิชาตามเกณฑ์ของคณะและกลุ่มวิชาเลือกหมวดศึกษาทั่วไป',
          subgroupName: 'วิชาบังคับ',
          earnCredit: 3,
          subjects: [
            {
              subject_id: '90642036',
              category: '1',
              group: '46',
              subgroup: '1',
              subject_tname: 'เตรียมความพร้อมสำหรับวิศวกร',
              subject_ename: 'PRE-ACTIVITIES FOR ENGINEERS',
              credit: 1,
            },
            {
              subject_id: '90642118',
              category: '1',
              group: '46',
              subgroup: '1',
              subject_tname: 'โปรแกรมคอมพิวเตอร์ประยุกต์ทางธุรกิจ',
              subject_ename: 'APPLICATION SOFTWARE FOR BUSSINESS',
              credit: 2,
            },
          ],
        },
        {
          category: 1,
          group: 46,
          subgroup: 2,
          credit1: 12,
          credit2: 12,
          categoryName: 'วิชาศึกษาทั่วไป',
          groupName: 'กลุ่มวิชาตามเกณฑ์ของคณะและกลุ่มวิชาเลือกหมวดศึกษาทั่วไป',
          subgroupName: 'วิชาเลือก',
          earnCredit: 12,
          subjects: [
            {
              subject_id: '90642003',
              category: '1',
              group: '46',
              subgroup: '3',
              subject_tname: 'ปฏิบัติงานตามทักษะด้านบุคคลและสนับสนุนวิชาชีพ 3',
              subject_ename:
                'PRACTICE UNDER PERSONAL AND PROFESSIONAL SKILLS 3',
              credit: 3,
            },
            {
              subject_id: '90642116',
              category: '1',
              group: '46',
              subgroup: '3',
              subject_tname: 'เมืองอัจฉริยะและนวัตกรรมเมือง',
              subject_ename: 'SMART CITY AND CITY INNOVATION',
              credit: 3,
            },
            {
              subject_id: '90643016',
              category: '1',
              group: '46',
              subgroup: '4',
              subject_tname: 'สนุกกับธุรกิจออนไลน์',
              subject_ename: 'FUN WITH ONLINE BUSINESS',
              credit: 3,
            },
            {
              subject_id: '90643019',
              category: '1',
              group: '46',
              subgroup: '4',
              subject_tname: 'เศรษฐศาสตร์กับการเป็นผู้ประกอบการ',
              subject_ename: 'ECONOMICS AND ENTREPRENEURSHIP',
              credit: 3,
            },
          ],
        },
        {
          category: 2,
          group: 100,
          subgroup: 1,
          credit1: 12,
          credit2: 12,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาแกน',
          subgroupName: 'วิชาแกนทางคณิตศาสตร์',
          earnCredit: 12,
          subjects: [
            {
              subject_id: '01076032',
              category: '2',
              group: '100',
              subgroup: '1',
              subject_tname: 'สมการอนุพันธ์และพีชคณิตเชิงเส้นพื้นฐาน',
              subject_ename:
                'ELEMENTARY DIFFERENTIAL EQUATIONS AND LINEAR ALGEBRA',
              credit: 3,
            },
            {
              subject_id: '01076140',
              category: '2',
              group: '100',
              subgroup: '1',
              subject_tname: 'แคลคูลัส 1',
              subject_ename: 'CALCULUS 1',
              credit: 3,
            },
            {
              subject_id: '01076141',
              category: '2',
              group: '100',
              subgroup: '1',
              subject_tname: 'แคลคูลัส 2',
              subject_ename: 'CALCULUS 2',
              credit: 3,
            },
            {
              subject_id: '01076253',
              category: '2',
              group: '100',
              subgroup: '1',
              subject_tname: 'ความน่าจะเป็นและสถิติ',
              subject_ename: 'PROBABILITY AND STATISTICS',
              credit: 3,
            },
          ],
        },
        {
          category: 2,
          group: 100,
          subgroup: 2,
          credit1: 18,
          credit2: 18,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาแกน',
          subgroupName: 'วิชาแกนทางวิศวกรรม',
          earnCredit: 18,
          subjects: [
            {
              subject_id: '01006004',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'การฝึกงานอุตสาหกรรม',
              subject_ename: 'INDUSTRIAL TRAINING',
              credit: 0,
            },
            {
              subject_id: '01076011',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'ระบบปฏิบัติการ',
              subject_ename: 'OPERATING SYSTEMS',
              credit: 3,
            },
            {
              subject_id: '01076012',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'โครงสร้างแบบดิสครีต',
              subject_ename: 'DISCRETE STRUCTURE',
              credit: 3,
            },
            {
              subject_id: '01076016',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'การเตรียมโครงงานวิศวกรรมคอมพิวเตอร์',
              subject_ename: 'COMPUTER ENGINEERING PROJECT PREPARATION',
              credit: 2,
            },
            {
              subject_id: '01076101',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'วิศวกรรมคอมพิวเตอร์เบื้องต้น',
              subject_ename: 'INTRODUCTION TO COMPUTER ENGINEERING',
              credit: 3,
            },
            {
              subject_id: '01076103',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'พื้นฐานการเขียนโปรแกรมคอมพิวเตอร์',
              subject_ename: 'PROGRAMMING FUNDAMENTAL',
              credit: 2,
            },
            {
              subject_id: '01076104',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'โครงงานโปรแกรมคอมพิวเตอร์',
              subject_ename: 'PROGRAMMING PROJECT',
              credit: 1,
            },
            {
              subject_id: '01076107',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'วงจรไฟฟ้าและอิเล็กทรอนิกส์',
              subject_ename: 'CIRCUITS AND ELECTRONICS',
              credit: 3,
            },
            {
              subject_id: '01076108',
              category: '2',
              group: '100',
              subgroup: '2',
              subject_tname: 'ปฏิบัติการวงจรไฟฟ้าและอิเล็กทรอนิกส์',
              subject_ename: 'CIRCUITS AND ELECTRONICS IN PRACTICE',
              credit: 1,
            },
          ],
        },
        {
          category: 2,
          group: 101,
          subgroup: 1,
          credit1: 43,
          credit2: 43,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาเฉพาะด้าน',
          subgroupName: 'วิชาบังคับ',
          earnCredit: 43,
          subjects: [
            {
              subject_id: '01076034',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'หลักการของกระบวนการพัฒนาซอฟต์แวร์',
              subject_ename: 'PRINCIPLES OF SOFTWARE DEVELOPMENT PROCESS',
              credit: 3,
            },
            {
              subject_id: '01076040',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'มาตรฐานและเทคโนโลยีเครือข่าย',
              subject_ename: 'INTERNETWORKING STANDARDS AND TECHNOLOGIES',
              credit: 3,
            },
            {
              subject_id: '01076041',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'ปฏิบัติการมาตรฐานและเทคโนโลยีเครือข่าย',
              subject_ename:
                'INTERNETWORKING STANDARDS AND TECHNOLOGIES IN PRACTICE',
              credit: 1,
            },
            {
              subject_id: '01076050',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'การประยุกต์และพัฒนาไมโครคอนโทรลเลอร์',
              subject_ename: 'MICROCONTROLLER APPLICATION AND DEVELOPMENT',
              credit: 3,
            },
            {
              subject_id: '01076051',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'โครงงานไมโครคอนโทรลเลอร์',
              subject_ename: 'MICROCONTROLLER PROJECT',
              credit: 1,
            },
            {
              subject_id: '01076105',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'การเขียนโปรแกรมเชิงวัตถุ',
              subject_ename: 'OBJECT ORIENTED PROGRAMMING',
              credit: 2,
            },
            {
              subject_id: '01076106',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'โครงงานโปรแกรมเชิงวัตถุ',
              subject_ename: 'OBJECT ORIENTED PROGRAMMING PROJECT',
              credit: 1,
            },
            {
              subject_id: '01076109',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'โครงสร้างข้อมูลเชิงวัตถุ',
              subject_ename: 'OBJECT ORIENTED DATA STRUCTURES',
              credit: 3,
            },
            {
              subject_id: '01076110',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'โครงงานโครงสร้างข้อมูลเชิงวัตถุ',
              subject_ename: 'OBJECT ORIENTED DATA STRUCTURES PROJECT',
              credit: 1,
            },
            {
              subject_id: '01076112',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'พื้นฐานระบบดิจิตอล',
              subject_ename: 'DIGITAL SYSTEM FUNDAMENTALS',
              credit: 3,
            },
            {
              subject_id: '01076113',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'ปฏิบัติการพื้นฐานระบบดิจิตอล',
              subject_ename: 'DIGITAL SYSTEM FUNDAMENTALS IN PRACTICE',
              credit: 1,
            },
            {
              subject_id: '01076114',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'องค์ประกอบและสถาปัตยกรรมคอมพิวเตอร์',
              subject_ename: 'COMPUTER ORGANIZATION AND ARCHITECTURE',
              credit: 3,
            },
            {
              subject_id: '01076115',
              category: '2',
              group: '101',
              subgroup: '5',
              subject_tname: 'ปฏิบัติการองค์ประกอบคอมพิวเตอร์\t',
              subject_ename: 'COMPUTER ORGANIZATION IN PRACTICE',
              credit: 1,
            },
            {
              subject_id: '01076116',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'เครือข่ายคอมพิวเตอร์',
              subject_ename: 'COMPUTER NETWORKS',
              credit: 3,
            },
            {
              subject_id: '01076117',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'ปฏิบัติการเครือข่ายคอมพิวเตอร์',
              subject_ename: 'COMPUTER NETWORKS IN PRACTICE',
              credit: 1,
            },
            {
              subject_id: '01076118',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'การดูแลแพลทฟอร์มระบบ',
              subject_ename: 'SYSTEM PLATFORM ADMINISTRATION',
              credit: 3,
            },
            {
              subject_id: '01076119',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'การพัฒนาโปรแกรมบนเว็บ',
              subject_ename: 'WEB APPLICATION DEVELOPMENT',
              credit: 3,
            },
            {
              subject_id: '01076120',
              category: '2',
              group: '101',
              subgroup: '3',
              subject_tname: 'โครงงานพัฒนาโปรแกรมบนเว็บ',
              subject_ename: 'WEB APPLICATION DEVELOPMENT PROJECT',
              credit: 1,
            },
            {
              subject_id: '01076121',
              category: '2',
              group: '101',
              subgroup: '4',
              subject_tname: 'ทฤษฎีการคำนวณ',
              subject_ename: 'THEORY OF COMPUTATION',
              credit: 3,
            },
            {
              subject_id: '01076263',
              category: '2',
              group: '101',
              subgroup: '2',
              subject_tname: 'ระบบฐานข้อมูล\t',
              subject_ename: 'DATABASE SYSTEMS',
              credit: 3,
            },
          ],
        },
        {
          category: 2,
          group: 101,
          subgroup: 6,
          credit1: 9,
          credit2: 9,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาเฉพาะด้าน',
          subgroupName: 'วิชาบังคับเลือก',
          earnCredit: 0,
          subjects: [],
        },
        {
          category: 2,
          group: 102,
          subgroup: 0,
          credit1: 6,
          credit2: 6,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาการศึกษาทางเลือก',
          subgroupName: 'ไม่สามารถทราบได้',
          earnCredit: 6,
          subjects: [
            {
              subject_id: '01076311',
              category: '2',
              group: '102',
              subgroup: '1',
              subject_tname: 'โครงงาน 1',
              subject_ename: 'PROJECT 1',
              credit: 3,
            },
            {
              subject_id: '01076312',
              category: '2',
              group: '102',
              subgroup: '1',
              subject_tname: 'โครงงาน 2',
              subject_ename: 'PROJECT 2',
              credit: 3,
            },
          ],
        },
        {
          category: 2,
          group: 103,
          subgroup: 0,
          credit1: 12,
          credit2: 12,
          categoryName: 'วิชาเฉพาะ',
          groupName: 'วิชาเลือกเฉพาะสาขา',
          subgroupName: 'ไม่สามารถทราบได้อีกแล้ว',
          earnCredit: 18,
          subjects: [
            {
              subject_id: '01076423',
              category: '2',
              group: '103',
              subgroup: '8',
              subject_tname: 'การวางแผนเชิงกลยุทธ์โดยใช้บอร์ดและการ์ดเกม',
              subject_ename: 'STRATEGIC PLANNING USING BOARD AND CARD GAME',
              credit: 3,
            },
            {
              subject_id: '01076566',
              category: '2',
              group: '103',
              subgroup: '4',
              subject_tname: 'ระบบสื่อผสม\t',
              subject_ename: 'MULTIMEDIA SYSTEMS',
              credit: 3,
            },
            {
              subject_id: '01076567',
              category: '2',
              group: '103',
              subgroup: '4',
              subject_tname: 'การประมวลผลภาพ\t',
              subject_ename: 'IMAGE PROCESSING',
              credit: 3,
            },
            {
              subject_id: '01076568',
              category: '2',
              group: '103',
              subgroup: '2',
              subject_tname: 'การปฏิสัมพันธ์ระหว่างมนุษย์และคอมพิวเตอร์',
              subject_ename: 'HUMAN COMPUTER INTERACTION',
              credit: 3,
            },
            {
              subject_id: '01076582',
              category: '2',
              group: '103',
              subgroup: '5',
              subject_tname: 'ปัญญาประดิษฐ์\t',
              subject_ename: 'ARTIFICIAL INTELLIGENCE',
              credit: 3,
            },
            {
              subject_id: '01076595',
              category: '2',
              group: '103',
              subgroup: '5',
              subject_tname: 'การสืบค้นสารสนเทศและการค้นหาเว็บ',
              subject_ename: 'INFORMATION STORAGE AND WEB SEARCH',
              credit: 3,
            },
          ],
        },
        {
          category: 3,
          group: 0,
          subgroup: 0,
          credit1: 6,
          credit2: 6,
          categoryName: 'เสรีรี่รี้รี๊รี๋',
          groupName: '',
          subgroupName: '',
          earnCredit: 0,
          subjects: [],
        },
      ],
      subjects: [
        {
          subject_id: '90644014',
          category: '1',
          group: '33,46',
          subgroup: '2,5',
          subject_tname: 'ภาษาอังกฤษเพื่อการสื่อสารทางวิชาชีพ',
          subject_ename: 'ENGLISH FOR PROFESSIONAL COMMUNICATION',
          credit: 3,
        },
        {
          subject_id: '90644033',
          category: '1',
          group: '33,46',
          subgroup: '2,5',
          subject_tname: 'การเขียนและการพูดในงานอาชีพ',
          subject_ename: 'WRITING AND SPEAKING IN THE PROFESSIONS',
          credit: 3,
        },
        {
          subject_id: '90644063',
          category: '1',
          group: '33,46',
          subgroup: '2,5',
          subject_tname: 'ภาษาญี่ปุ่นเพื่อการท่องเที่ยว',
          subject_ename: 'JAPANESE FOR TRAVEL',
          credit: 3,
        },
        {
          subject_id: '01076035',
          category: '2',
          group: '101,103',
          subgroup: '8,9',
          subject_tname: 'กระบวนการพัฒนาซอฟต์แวร์เชิงปฏิบัติ',
          subject_ename: 'SOFTWARE DEVELOPMENT PROCESS IN PRACTICE',
          credit: 3,
        },
        {
          subject_id: '01076036',
          category: '2',
          group: '101,103',
          subgroup: '8,9',
          subject_tname: 'การออกแบบประสบการณ์และส่วนติดต่อผู้ใช้',
          subject_ename: 'USER EXPERIENCE AND USER INTERFACE DESIGN',
          credit: 2,
        },
        {
          subject_id: '01076037',
          category: '2',
          group: '101,103',
          subgroup: '8,9',
          subject_tname: 'โครงงานออกแบบประสบการณ์และส่วนติดต่อผู้ใช้',
          subject_ename: 'USER EXPERIENCE AND USER INTERFACE PROJECT',
          credit: 1,
        },
        {
          subject_id: '01076042',
          category: '2',
          group: '101,103',
          subgroup: '9',
          subject_tname: 'ความมั่นคงข้อมูลและคอมพิวเตอร์',
          subject_ename: 'INFORMATION AND COMPUTER SECURITY',
          credit: 3,
        },
      ],
    },
    unknowDetail: [
      {
        subject_subject_id: '90592004',
        subject_subject_tname: 'วัฒนธรรมร่วมสมัย',
        subject_subject_ename: 'CONTEMPORARY CULTURE',
        subject_credit: 3,
      },
      {
        subject_subject_id: '96642111',
        subject_subject_tname: 'FUN WITH CODING',
        subject_subject_ename: 'FUN WITH CODING',
        subject_credit: 3,
      },
    ],
  },
  timestamp: '2025-01-22 06:18:12',
  meta: {},
};

export const mockSelectedCurriGroup: CurriGroup = {
  faculty: {
    label: 'วิศวกรรมศาสตร์',
    value: '01',
    children: [
      {
        label: 'วิศวกรรมคอมพิวเตอร์',
        value: '05',
        children: [
          {
            label: 'วิศวกรรมคอมพิวเตอร์',
            value: '06',
            children: [
              {
                label: '2564',
                value: '2564',
              },
            ],
          },
        ],
      },
    ],
  },
  department: {
    label: 'วิศวกรรมคอมพิวเตอร์',
    value: '05',
    children: [
      {
        label: 'วิศวกรรมคอมพิวเตอร์',
        value: '06',
        children: [
          {
            label: '2564',
            value: '2564',
          },
        ],
      },
    ],
  },
  curriculum: {
    label: 'วิศวกรรมคอมพิวเตอร์',
    value: '06',
    children: [
      {
        label: '2564',
        value: '2564',
      },
    ],
  },
  curriculumYear: {
    label: '2564',
    value: '2564',
  },
};
